name: Deploy Documentation on Release

on:
  workflow_dispatch:

jobs:
  docs:
    uses: SYMSCAE/release-scripts/.github/workflows/_release-docs.yml@d64728a2004299aab35d9316432a10a50a7680b2
    with:
      project: diffpy.srreal
      c_extension: true
      submodules: recursive
      python_version: 0
      headless: false
